### ISSUE TITLE
开启 smooth 吧

### ISSUE THREAD

**Issue by DaiwenZh5** [k-dylan/vue-catalog#1]
https://github.com/k-dylan/vue-catalog/blob/398e724ecbdb962280cfec92988dc185d247eda2/src/components/catalogItem.vue#L39
用了之后效果都实现了，就是滑动不流畅，太生硬了，这里应该把参数暴露出去，或者使用配置 smooth 替换空参

**Comment by k-dylan** [comment]
我把showTile方式暴露出来了！
